name: music-genre-classification
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=2.0.0
  - torchaudio>=2.0.0
  - torchvision>=0.15.0
  - librosa>=0.10.0
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - jupyter
  - pip
  - pip:
    - streamlit>=1.25.0
    - plotly>=5.0.0
    - pyyaml>=6.0
    - pytest>=7.0.0
    - black>=22.0.0
