# 鍩虹閰嶇疆鏂囦欢
project:
  name: music-genre-classification
  version: 1.0.0

data:
  dataset: gtzan
  sample_rate: 22050
  duration: 3.0
  n_mels: 128
  n_fft: 2048
  hop_length: 512

training:
  batch_size: 32
  epochs: 100
  learning_rate: 0.001
  optimizer: adam
  early_stopping_patience: 10

model:
  architecture: cnn
  dropout: 0.3
  num_classes: 10
